name: vs_node_view
description: "A Visual Scripting toolkit to create and use your own VS widgets."
version: 2.1.0
repository: https://github.com/Cunibon/vs_node_view

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
